export const UNIVERSITY_OPTIONS = [
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "University of Cambridge",
  "University of Oxford",
  "Columbia University",
  "University of California, Berkeley",
  "University of Chicago",
  "Princeton University",
  "Yale University",
  "University of Pennsylvania",
  "California Institute of Technology",
  "University of California, Los Angeles",
  "Imperial College London",
  "University College London",
  "ETH Zürich",
  "École Polytechnique Fédérale de Lausanne",
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Melbourne",
  "Australian National University",
  "University of Sydney",
  "University of New South Wales",
  "National University of Singapore",
  "Nanyang Technological University",
  "Peking University",
  "Tsinghua University",
  "University of Tokyo",
  "Kyoto University",
  "Seoul National University",
  "University of Hong Kong",
  "University of Michigan",
  "University of Washington",
  "New York University",
  "University of Illinois Urbana-Champaign",
  "University of Wisconsin–Madison",
  "University of Texas at Austin",
  "Duke University",
  "Johns Hopkins University",
  "Cornell University",
  "Carnegie Mellon University",
  "Georgia Institute of Technology",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Glasgow",
  "University of Warwick",
  "University of Leeds",
  "Trinity College Dublin",
  "University of Copenhagen",
  "University of Helsinki",
  "University of Oslo",
  "University of Stockholm",
  "University of Amsterdam",
  "Leiden University",
  "University of Groningen",
  "KU Leuven",
  "Ghent University",
  "Ludwig Maximilian University of Munich",
  "Technical University of Munich",
  "University of Heidelberg",
  "University of Freiburg",
  "University of Bonn",
  "Sorbonne University",
  "Université PSL",
  "École Polytechnique",
  "University of Barcelona",
  "University of Madrid (Complutense)",
  "University of Lisbon",
  "University of Porto",
  "University of São Paulo",
  "Pontifical Catholic University of Chile",
  "University of Buenos Aires",
  "University of Cape Town",
  "American University in Cairo",
  "King Saud University",
  "University of Zurich",
  "University of Geneva",
  "University of Bern",
  "University of St. Gallen",
  "University of Basel",
  "University of Lausanne",
  "University of Fribourg",
  "University of Neuchâtel",
];

export const filterUniversities = (query: string, limit = 6): string[] => {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return [];
  return UNIVERSITY_OPTIONS.filter((name) => name.toLowerCase().includes(trimmed)).slice(0, limit);
};
